---
- name: My First Playbook
  hosts: all
  tasks:
  - name: Print the Running Users Id
    command:
      argv: id
  - name: Install the Apache HTTP Server
    yum:
      name: httpd
      state: present